# path: repsy-repo/docker-compose.yml

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: repsy
      POSTGRES_USER: repsy
      POSTGRES_PASSWORD: repsy
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U repsy"]
      interval: 10s
      retries: 5

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 20s
      retries: 5

  app:
    # artık root’taki Dockerfile’ı kullanacağız
    build: .
    image: repsy/repo-app:1.0.0
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/repsy
      SPRING_DATASOURCE_USERNAME: repsy
      SPRING_DATASOURCE_PASSWORD: repsy
      storageStrategy: object-storage
      storage.minio.endpoint: http://minio:9000
      storage.minio.accessKey: minio
      storage.minio.secretKey: minio123
      storage.minio.bucket: repsy
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
